# Site settings
title: 大与可读什么
header-img: "img/green.jpg"
tagline: "cn"  
description: "李毅奇|读而立·写而生"  
baseurl: ""
encoding: utf-8



# About/contact
owner: 
  name: " yq"

paginate: 8
plugins: [jekyll-paginate]

