# Site settings
title: 一起修仙
header-img: "img/green.jpg"
tagline: "cn"  
description: "李毅奇|yq·xx"  
baseurl: ""
encoding: utf-8



# About/contact
owner: 
  name: " yq"

paginate: 8
plugins: [jekyll-paginate]

